---
deployment:
  tasks:
    - export DEPLOYPATH=/home/omaniservers/public_html/phpgit
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R * $DEPLOYPATH/
    - /bin/cp .htaccess $DEPLOYPATH/
    - /bin/chmod 644 $DEPLOYPATH/*.php
    - /bin/chmod 755 $DEPLOYPATH/
    - /bin/chmod -R 755 $DEPLOYPATH/config/
    - /bin/chmod -R 755 $DEPLOYPATH/includes/
    - /bin/chmod 777 $DEPLOYPATH  # Temporarily allow write access for logs 